apiVersion: v1
kind: Service
metadata:
  name: kord-user-portal
  namespace: default
  labels:
    app: kord-user-portal
spec:
  type: NodePort
  selector:
    app: kord-user-portal
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
